### ISSUE TITLE
Linux - Not Finding Raylib Beef

### ISSUE THREAD

**Issue by joseph-montanez** [M0n7y5/raylib-beef#9]
I am not sure if this is an issue with this library or Beef. No matter what I do I get:

```
ERROR: Type could not be found (are you missing a using directive or library reference?) at line 2:14 in /home/joseph/Documents/beef-game/src/Program.bf
using static raylib_beef.Raylib;
             ^^^^^^^^^^^
```

It seems like Beef cannot parse the library correctly. Here is a zip of raylib-beef inside of the example you provided with flags on my end: https://drive.google.com/file/d/1l1yKDCufm7vB8m8zG_ykqykLvpR4Qdza/view?usp=sharing

Here is the repo:
https://github.com/joseph-montanez/beef-game

    git clone --recurse-submodules https://github.com/joseph-montanez/beef-game.git

**Comment by M0n7y5** [comment]
Oh i didnt test it on Linux. Right know i am focused on Windows development. Also it seems you didnt follow tutorial on how to get started with simple example code. U need to add raylib as a dependency to your project. Dont know how to achieve it on Linux since IDE is running only on windows right now.

**Comment by M0n7y5** [comment]
Also i am gonna add info about Windows focused development of this library to Readme.md

**Comment by joseph-montanez** [comment]
I ended up re-cloning your repository into my project and it works just fine, but will open another ticket for a different issue. Please ignore, it runs fine on Linux :)
